version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:

    docker:
      - image: cimg/python:3.6

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: mtalg/requirements.txt
      - run:
          name: Run tests
          command: pip install pytest
          command: pip install pytest-cov
          command: pytest mtalg/testing/rng_tests.py

workflows:
  sample: 
    jobs:
      - build-and-test
