version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:

    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: mtalg/dev-requirements.txt
      - run:
          name: Run tests
          command: pytest mtalg/testing/ --cov-config=.coveragerc --cov=mtalg mtalg/testing/ --junitxml=unit.xml --cov-report xml=cov.xml
      - run:
          name: Send to Codacy
          command: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r cov.xml

workflows:
  sample: 
    jobs:
      - build-and-test
