image: "python:3.7"

stages:
  - build
  - testing
  - deploy

before_script:
  - python --version
  - apt-get update -y
  - apt-get install libsasl2-dev
  - apt-get install -y jq curl
  - pip3 install -r mtalg/requirements.txt


test_rng:
  stage: testing
  script:
    - echo "Testing random number generation..."

test_em_algebra:
  stage: testing
  script:
    - echo "Testing element-wise algebra..."
    - python3 setup.py install
    - python3 mtalg/testing/em_algebra_tests.py
    - echo "All tests passed."

build:
  stage: build
  script:
    - echo "Building on UNIX..."
    - python3 setup.py install

make-badge:
  stage: deploy
  script:
    - python3 mtalg/__res/update_badge.py


deploy:
  stage: deploy
  script:
    - pip install twine
    - python3 setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${ARTIFACTORY_PASS} TWINE_USERNAME=${ARTIFACTORY_USER} python -m twine upload --repository-url https://artifactory.sofa.dev/artifactory/api/pypi/pypi-local dist/*

